<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="$(MSBuildThisFileDirectory)MappaVersion.targets"/>
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageOutputPath>../.packages</PackageOutputPath>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>
    <PropertyGroup>
        <Version>$(MappaVersion)</Version>
        <Authors>Stefano Anelli</Authors>
        <Company>Stefano Anelli</Company>
        <NeutralLanguage>en</NeutralLanguage>
        <Copyright>Stefano Anelli</Copyright>
    </PropertyGroup>
</Project>