// <copyright file="CompilationUnitSyntaxAssertions.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mappa.Generator.Tests.Assertions;

/// <summary>
/// Assertions for <see cref="SyntaxTree"/>.
/// </summary>
public sealed class CompilationUnitSyntaxAssertions
    : ObjectAssertions<CompilationUnitSyntax, CompilationUnitSyntaxAssertions>
{
    private readonly SemanticModel semanticModel;
    private readonly Compilation compilation;

    /// <summary>
    /// Initializes a new instance of the <see cref="CompilationUnitSyntaxAssertions"/> class.
    /// </summary>
    /// <param name="value">The target of the assertions.</param>
    /// <param name="semanticModel">The semantic model.</param>
    /// <param name="compilation">The compilation unit.</param>
    public CompilationUnitSyntaxAssertions(
        CompilationUnitSyntax value,
        SemanticModel semanticModel,
        Compilation compilation)
        : base(value)
    {
        this.semanticModel = semanticModel;
        this.compilation = compilation;
    }

    /// <summary>
    /// Check that the header of the file contains a comment
    /// explaining that this is an auto generated file.
    /// </summary>
    /// <returns>The assertions.</returns>
    public CompilationUnitSyntaxAssertions HaveCommentHeader()
    {
        this.Subject.HasLeadingTrivia.Should().BeTrue();
        var leadingTrivia = this.Subject.GetLeadingTrivia()
            .Select(trivia => trivia.ToString())
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .ToArray();
        leadingTrivia.Should().HaveCount(6);
        var mappaGeneratorVersion = MappaGeneratorConsts.MappaGeneratorVersion.ToString();
        leadingTrivia[0].Should().Be("// <auto-generated>");
        leadingTrivia[1].Should().Be("//    <tool-name>Mappa</tool-name>");
        leadingTrivia[2].Should().Be($"//    <tool-version>{mappaGeneratorVersion}</tool-version>");
        leadingTrivia[3].Should().MatchRegex("\\/\\/    \\<timestamp\\>(.*)\\<\\/timestamp\\>");
        leadingTrivia[4].Should()
            .Be("//    <note>This is an autogenerated file: edit to this file might be lost.</note>");
        leadingTrivia[5].Should().Be("// </auto-generated>");

        return this;
    }

    /// <summary>
    /// Assert the compilation unit contains a file scoped namespace.
    /// </summary>
    /// <returns>The file scoped namespace declaration syntax assertions.</returns>
    public FileScopedNamespaceDeclarationSyntaxAssertions HaveFileScopedNamespace()
    {
        var fileScopedNamespaceDeclarationSyntaxes =
            this.Subject.ChildNodes().OfType<FileScopedNamespaceDeclarationSyntax>().ToArray();
        fileScopedNamespaceDeclarationSyntaxes.Should().HaveCount(1);

        return new FileScopedNamespaceDeclarationSyntaxAssertions(
            fileScopedNamespaceDeclarationSyntaxes.Single(),
            this.semanticModel,
            this.compilation);
    }
}