// <copyright file="MapFileGeneratorBuilder.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

using System;
using System.Text;

using Mappa.Generator.Models;
using Mappa.Generator.Models.Helpers;

namespace Mappa.Generator.Builders;

/// <summary>
/// Build a map for a file.
/// </summary>
internal sealed class MapFileGeneratorBuilder
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MapFileGeneratorBuilder"/> class.
    /// </summary>
    /// <param name="classContext">The class generator context.</param>
    public MapFileGeneratorBuilder(MappaClassGeneratorContext classContext)
    {
        this.ClassContext = classContext;
        this.HintName = $"{this.ClassContext.ClassDeclarationSyntax.Identifier}.{Guid.NewGuid()}.g.cs";
    }

    /// <summary>
    /// Gets the hint name.
    /// </summary>
    internal string HintName { get; }

    /// <summary>
    /// Gets the class generator context.
    /// </summary>
    internal MappaClassGeneratorContext ClassContext { get; }

    /// <summary>
    /// Build the source code.
    /// </summary>
    /// <returns>The source code.</returns>
    internal string BuildSource()
    {
        var declarationSyntax = this.ClassContext.ClassDeclarationSyntax;
        var builder = new IndentStringBuilder();
        builder.Append($"// <description>");
        builder.Append($"//    <class-name>{declarationSyntax.Identifier}</class-name>");
        builder.Append($"//    <tool-name>Mappa</tool-name>");
        builder.Append($"//    <timestamp>{DateTime.UtcNow.ToString("R")}</timestsamp>");
        builder.Append($"//    <note>This is an autogenerated file: edit to this file might be lost.</note>");
        builder.Append($"// </description>");

        return string.Empty;
    }
}