// <copyright file="MappaFileBuilder.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

using Mappa.Generator.Models;

namespace Mappa.Generator.Builders;

/// <summary>
/// Build a map for a file.
/// </summary>
internal sealed class MappaFileBuilder
    : IMappaBuilder
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MappaFileBuilder"/> class.
    /// </summary>
    /// <param name="classContext">The class generator context.</param>
    public MappaFileBuilder(MappaClassGeneratorContext classContext)
    {
        this.ClassContext = classContext;
        this.HintName = $"{this.ClassContext.ClassSymbol.ToDisplayString()}.g.cs";
    }

    /// <summary>
    /// Gets the hint name.
    /// </summary>
    internal string HintName { get; }

    /// <summary>
    /// Gets the class generator context.
    /// </summary>
    private MappaClassGeneratorContext ClassContext { get; }

    /// <inheritdoc/>
    public string BuildSource(MappaBuilderContext context, MappaGlobalOptions mappaGlobalOptions)
    {
        // Build the source for the class.
        var classSourceCode = new MappaClassBuilder(this.ClassContext).BuildSource(context, mappaGlobalOptions);

        // Add the namespace to the class code.
        var classSourceCodeWithNamespace = new MappaNamespaceBuilder(this.ClassContext, classSourceCode).BuildSource(context, mappaGlobalOptions);

        var builder = new PrettyCode.StringBuilder();

        // Add the file command description and the class code with namespace.
        builder
            .AppendLine("// <auto-generated>")
            .AppendLine("//    <tool-name>Mappa</tool-name>")
            .AppendLine($"//    <tool-version>{MappaGeneratorConsts.MappaGeneratorVersion}</tool-version>")
            .AppendLine($"//    <timestamp>{DateTime.UtcNow:R}</timestamp>")
            .AppendLine("//    <note>This is an autogenerated file: edit to this file might be lost.</note>")
            .AppendLine("// </auto-generated>");
        builder.AppendEmptyLine();

        // Emit file-local accessors before the file-scoped namespace so they remain in the
        // global namespace (everything after `namespace X;` belongs to that namespace).
        var inaccessibleAccessorsSource = context.InaccessibleAccessors.BuildSource();
        if (!string.IsNullOrWhiteSpace(inaccessibleAccessorsSource))
        {
            builder.AppendLine(inaccessibleAccessorsSource);
            builder.AppendEmptyLine();
        }

        builder.AppendLine(classSourceCodeWithNamespace);

        return builder.ToString();
    }
}