// <copyright file="MappaDependencyInjectionFileBuilder.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

using System.Collections.Immutable;

using Mappa.Generator.Models;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mappa.Generator.Builders;

/// <summary>
/// Builds the generated source for a <see cref="Mappa.Attributes.MappaDependencyInjectionAttribute"/> registrar.
/// </summary>
internal sealed class MappaDependencyInjectionFileBuilder
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MappaDependencyInjectionFileBuilder"/> class.
    /// </summary>
    /// <param name="classDeclarationSyntax">The registrar class syntax.</param>
    /// <param name="classSymbol">The registrar class symbol.</param>
    /// <param name="attributeData">The parsed attribute data.</param>
    /// <param name="mappers">The mapper types to register, with their eligible interfaces.</param>
    internal MappaDependencyInjectionFileBuilder(
        ClassDeclarationSyntax classDeclarationSyntax,
        INamedTypeSymbol classSymbol,
        MappaDependencyInjectionAttributeData attributeData,
        ImmutableArray<(INamedTypeSymbol Mapper, ImmutableArray<INamedTypeSymbol> Interfaces)> mappers)
    {
        this.ClassDeclarationSyntax = classDeclarationSyntax;
        this.ClassSymbol = classSymbol;
        this.AttributeData = attributeData;
        this.Mappers = mappers;
        this.HintName = $"{this.ClassSymbol.ToDisplayString()}.DependencyInjection.g.cs";
    }

    /// <summary>
    /// Gets the hint name for <see cref="Microsoft.CodeAnalysis.SourceProductionContext.AddSource(string,string)"/>.
    /// </summary>
    internal string HintName { get; }

    private ClassDeclarationSyntax ClassDeclarationSyntax { get; }

    private INamedTypeSymbol ClassSymbol { get; }

    private MappaDependencyInjectionAttributeData AttributeData { get; }

    private ImmutableArray<(INamedTypeSymbol Mapper, ImmutableArray<INamedTypeSymbol> Interfaces)> Mappers { get; }

    /// <summary>
    /// Builds the generated source text.
    /// </summary>
    /// <returns>The generated source.</returns>
    internal string BuildSource()
    {
        var builder = new PrettyCode.StringBuilder();
        builder
            .AppendLine("// <auto-generated>")
            .AppendLine("//    <tool-name>Mappa</tool-name>")
            .AppendLine($"//    <tool-version>{MappaGeneratorConsts.MappaGeneratorVersion}</tool-version>")
            .AppendLine($"//    <timestamp>{DateTime.UtcNow:R}</timestamp>")
            .AppendLine("//    <note>This is an autogenerated file: edit to this file might be lost.</note>")
            .AppendLine("// </auto-generated>");
        builder.AppendEmptyLine();
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendEmptyLine();

        var classSource = this.BuildClassSource();
        var @namespace = this.ClassSymbol.ContainingNamespace.ToDisplayString();

        if (this.ClassDeclarationSyntax.Parent is FileScopedNamespaceDeclarationSyntax)
        {
            builder.AppendLine($"namespace {@namespace};");
            builder.AppendEmptyLine();
            builder.AppendLine(classSource);
        }
        else if (this.ClassDeclarationSyntax.Parent is NamespaceDeclarationSyntax)
        {
            builder.AppendLine($"namespace {@namespace}");
            using (builder.CurlyBracesBlock())
            {
                builder.AppendLine(classSource);
            }
        }
        else
        {
            builder.AppendLine(classSource);
        }

        return builder.ToString();
    }

    private static string GetAddMethodName(MappaDependencyInjectionServiceLifetime serviceLifetime)
        => serviceLifetime switch
        {
            MappaDependencyInjectionServiceLifetime.Scoped => "AddScoped",
            MappaDependencyInjectionServiceLifetime.Transient => "AddTransient",
            _ => "AddSingleton",
        };

    private static string GetAccessibilityKeyword(MappaDependencyInjectionMethodAccessibility accessibility)
        => accessibility switch
        {
            MappaDependencyInjectionMethodAccessibility.Private => "private",
            MappaDependencyInjectionMethodAccessibility.Protected => "protected",
            MappaDependencyInjectionMethodAccessibility.Internal => "internal",
            MappaDependencyInjectionMethodAccessibility.ProtectedInternal => "protected internal",
            _ => "public",
        };

    private static void AppendInterfaceOnlyMapperRegistrations(
        PrettyCode.StringBuilder builder,
        string addMethodName,
        string mapperTypeName,
        ImmutableArray<INamedTypeSymbol> interfaces)
    {
        foreach (var @interface in interfaces)
        {
            var interfaceTypeName = $"global::{@interface.ToDisplayString()}";
            builder.AppendLine($"services.{addMethodName}<{interfaceTypeName}, {mapperTypeName}>();");
        }
    }

    private static void AppendInterfaceAndClassMapperRegistrations(
        PrettyCode.StringBuilder builder,
        string addMethodName,
        string mapperTypeName,
        ImmutableArray<INamedTypeSymbol> interfaces)
    {
        builder.AppendLine($"services.{addMethodName}<{mapperTypeName}>();");
        foreach (var @interface in interfaces)
        {
            var interfaceTypeName = $"global::{@interface.ToDisplayString()}";
            builder.AppendLine(
                $"services.{addMethodName}<{interfaceTypeName}, {mapperTypeName}>(serviceProvider => serviceProvider.GetRequiredService<{mapperTypeName}>());");
        }
    }

    private string BuildClassSource()
    {
        var builder = new PrettyCode.StringBuilder();
        var syntaxModifiers = string.Join(
            " ",
            this.ClassDeclarationSyntax.Modifiers.Select(modifier => modifier.Text));
        if (!syntaxModifiers.Contains("partial", StringComparison.Ordinal))
        {
            syntaxModifiers = string.IsNullOrWhiteSpace(syntaxModifiers)
                ? "partial"
                : $"{syntaxModifiers} partial";
        }

        builder.AppendLine($"{syntaxModifiers} class {this.ClassDeclarationSyntax.Identifier.Text}");
        using (builder.CurlyBracesBlock())
        {
            builder.AppendLine(this.BuildMethodSource());
        }

        return builder.ToString();
    }

    private string BuildMethodSource()
    {
        var builder = new PrettyCode.StringBuilder();
        var methodName = this.AttributeData.ResolveMethodName(this.ClassDeclarationSyntax.Identifier.Text);
        var accessibility = GetAccessibilityKeyword(this.AttributeData.Accessibility);
        var addMethodName = GetAddMethodName(this.AttributeData.ServiceLifetime);
        var isStaticClass = this.ClassSymbol.IsStatic;
        var isExtension = isStaticClass && this.AttributeData.ExtensionMethod;

        var modifiers = isStaticClass || isExtension
            ? $"{accessibility} static"
            : accessibility;
        var parameter = isExtension
            ? "this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services"
            : "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services";

        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Registers all <c>[Mappa]</c> mapper types from this assembly into <paramref name=\"services\"/>.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("/// <param name=\"services\">The service collection to register mappers into.</param>");
        builder.AppendLine("/// <returns>The same <paramref name=\"services\"/> instance for chaining.</returns>");
        builder.AppendLine($"{modifiers} global::Microsoft.Extensions.DependencyInjection.IServiceCollection {methodName}({parameter})");
        using (builder.CurlyBracesBlock())
        {
            this.AppendMapperServiceRegistrations(builder, addMethodName);
            builder.AppendLine("return services;");
        }

        return builder.ToString();
    }

    private void AppendMapperServiceRegistrations(PrettyCode.StringBuilder builder, string addMethodName)
    {
        foreach (var (mapper, interfaces) in this.Mappers)
        {
            var mapperTypeName = $"global::{mapper.ToDisplayString()}";
            switch (this.AttributeData.InjectInterfaces)
            {
                case MappaDependencyInjectionInjectInterfaces.InterfaceOnly:
                    AppendInterfaceOnlyMapperRegistrations(builder, addMethodName, mapperTypeName, interfaces);
                    break;

                case MappaDependencyInjectionInjectInterfaces.InterfaceAndClass:
                    AppendInterfaceAndClassMapperRegistrations(builder, addMethodName, mapperTypeName, interfaces);
                    break;

                default:
                    builder.AppendLine($"services.{addMethodName}<{mapperTypeName}>();");
                    break;
            }
        }
    }
}