// <copyright file="MappaFileBuilder.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

using System;
using System.Text;

using Mappa.Generator.Models;
using Mappa.Generator.Models.Helpers;

using Microsoft.CodeAnalysis.CSharp;

namespace Mappa.Generator.Builders;

/// <summary>
/// Build a map for a file.
/// </summary>
internal sealed class MappaFileBuilder
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MappaFileBuilder"/> class.
    /// </summary>
    /// <param name="classContext">The class generator context.</param>
    public MappaFileBuilder(MappaClassGeneratorContext classContext)
    {
        this.ClassContext = classContext;
        this.HintName = $"{this.ClassContext.ClassDeclarationSyntax.Identifier}.{Guid.NewGuid()}.g.cs";
    }

    /// <summary>
    /// Gets the hint name.
    /// </summary>
    internal string HintName { get; }

    /// <summary>
    /// Gets the class generator context.
    /// </summary>
    internal MappaClassGeneratorContext ClassContext { get; }

    /// <summary>
    /// Build the source code.
    /// </summary>
    /// <returns>The source code.</returns>
    internal string BuildSource()
    {
        var declarationSyntax = this.ClassContext.ClassDeclarationSyntax;
        var builder = new IndentStringBuilder();
        builder.AppendLine($"// <description>")
               .AppendLine($"//    <class-name>{declarationSyntax.Identifier}</class-name>")
               .AppendLine($"//    <tool-name>Mappa</tool-name>")
               .AppendLine($"//    <timestamp>{DateTime.UtcNow.ToString("R")}</timestsamp>")
               .AppendLine($"//    <note>This is an autogenerated file: edit to this file might be lost.</note>")
               .AppendLine($"// </description>");
        return string.Empty;
    }
}