<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(MSBuildThisFileDirectory)../MappaVersion.targets"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <WarningsNotAsErrors>MP00000</WarningsNotAsErrors>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mappa" Version="$(MappaVersion)" />
        <PackageReference Include="AutoBogus" Version="2.13.1" />
        <PackageReference Include="AutoMapper" Version="13.0.1" />
        <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
        <PackageReference Include="Mapster" Version="7.4.0" />
        <PackageReference Include="Riok.Mapperly" Version="4.1.1" />
        <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.6.0.109712">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Mappa.Generator" Version="$(MappaVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="../stylecop.json" />
    </ItemGroup>

</Project>