syntax = "proto3";

option csharp_namespace = "Mappa.Samples.Models";

import "google/protobuf/timestamp.proto";

// Protobuf model for the CountingValues enum.
enum ProtobufCountingValues
{
  // First one.
  One = 0;

  // Second two.
  Two = 1;

  // Third value.
  Three = 2;
}

// Source protobuf model with optionals.
message SourceProtobufOptionalModel
{
  // An integer value.
  optional int32 ParamA = 1;

  // An enum value.
  optional ProtobufCountingValues ParamB = 2;
}

// Target protobuf model with optionals.
message TargetProtobufOptionalModel
{
  // An integer value.
  optional int32 ParamA = 1;

  // An enum value.
  optional ProtobufCountingValues ParamB = 2;
}

// Target protobuf model with collections.
message TargetProtobufClassWithCollections
{
  // A list of repeated strings.
  repeated string PropertyA = 1;

  // A map from string to integers.
  map<string, int32> PropertyG = 2;
}

// Source model containing common types that can be mapped
// using Protobuf mappa dependency package.
message MappaDependencyTargetModel
{
    // A timestamp.
    google.protobuf.Timestamp TimeStamp = 1;
}