// <copyright file="CompilationUnitSyntaxAssertionsExtensions.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

namespace Mappa.Generator.Tests.Assertions.Extensions;

/// <summary>
/// Extensions for <see cref="CompilationUnitSyntaxAssertions"/>.
/// </summary>
internal static class CompilationUnitSyntaxAssertionsExtensions
{
    /// <summary>
    /// Check that the header of the file contains a comment
    /// explaining that this is an auto generated file.
    /// </summary>
    /// <param name="this">The compilation unit syntax assertions.</param>
    /// <returns>The assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveCommentHeader(this CompilationUnitSyntaxAssertions @this)
    {
        ArgumentNullException.ThrowIfNull(@this);

        @this.Subject.HasLeadingTrivia.Should().BeTrue();
        var leadingTrivia = @this.Subject.GetLeadingTrivia()
            .Select(trivia => trivia.ToString())
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .ToArray();
        leadingTrivia.Should().HaveCount(6);
        var mappaGeneratorVersion = MappaGeneratorConsts.MappaGeneratorVersion.ToString();
        leadingTrivia[0].Should().Be("// <auto-generated>");
        leadingTrivia[1].Should().Be("//    <tool-name>Mappa</tool-name>");
        leadingTrivia[2].Should().Be($"//    <tool-version>{mappaGeneratorVersion}</tool-version>");
        leadingTrivia[3].Should().MatchRegex("\\/\\/    \\<timestamp\\>(.*)\\<\\/timestamp\\>");
        leadingTrivia[4].Should()
            .Be("//    <note>This is an autogenerated file: edit to this file might be lost.</note>");
        leadingTrivia[5].Should().Be("// </auto-generated>");

        return @this;
    }

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="expectedGeneratedMethodsCount">The expected number of generated methods.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedMethodsCount,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveDefaultMapMethod(
            returnType,
            returnTypeNullableAnnotation,
            parameterType,
            parameterNullableAnnotation,
            expectedGeneratedMethodsCount,
            false,
            NullableSetup.Enable,
            PragmaWarning.NoBlock,
            bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="expectedGeneratedMethodsCount">The expected number of generated methods.</param>
    /// <param name="nullableSetup">The nullable setup.</param>
    /// <param name="pragmaWarningSetting">The pragma warning setting.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedMethodsCount,
        NullableSetup nullableSetup,
        PragmaWarning pragmaWarningSetting,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveDefaultMapMethod(
            returnType,
            returnTypeNullableAnnotation,
            parameterType,
            parameterNullableAnnotation,
            expectedGeneratedMethodsCount,
            false,
            nullableSetup,
            pragmaWarningSetting,
            bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        string parameterType,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveMapMethod(
            "Mapper",
            [SyntaxKind.PublicKeyword, SyntaxKind.SealedKeyword, SyntaxKind.PartialKeyword],
            "Map",
            [SyntaxKind.PublicKeyword, SyntaxKind.PartialKeyword],
            returnType,
            NullableAnnotation.NotAnnotated,
            "input",
            parameterType,
            NullableAnnotation.NotAnnotated,
            1,
            bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => HaveDefaultMapMethod(@this, returnType, returnTypeNullableAnnotation, parameterType, parameterNullableAnnotation, 1, bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="nullableSetup">The nullable setup.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        NullableSetup nullableSetup,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => HaveDefaultMapMethod(@this, returnType, returnTypeNullableAnnotation, parameterType, parameterNullableAnnotation, 1, nullableSetup, PragmaWarning.NoBlock, bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="nullableSetup">The nullable setup.</param>
    /// <param name="pragmaWarning">The pragma warning setup.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        NullableSetup nullableSetup,
        PragmaWarning pragmaWarning,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => HaveDefaultMapMethod(@this, returnType, returnTypeNullableAnnotation, parameterType, parameterNullableAnnotation, 1, nullableSetup, pragmaWarning, bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method.
    /// </summary>
    /// <param name="this">The compilation unit syntax assertions.</param>
    /// <param name="className">The name of the class.</param>
    /// <param name="classModifiers">The class modifiers.</param>
    /// <param name="methodName">The name of the method.</param>
    /// <param name="methodModifiers">The method modifiers.</param>
    /// <param name="isExtensionMethod">The method is an extension method.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The nullable annotation on the return type.</param>
    /// <param name="parameterName">The name of the parameter.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The nullable annotation of the parameter.</param>
    /// <param name="expectedGeneratedCount">The number of expected methods generated.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string className,
        SyntaxKind[] classModifiers,
        string methodName,
        SyntaxKind[] methodModifiers,
        bool isExtensionMethod,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterName,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedCount,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveMapMethod(
            className,
            classModifiers,
            methodName,
            methodModifiers,
            isExtensionMethod,
            returnType,
            returnTypeNullableAnnotation,
            parameterName,
            parameterType,
            null,
            parameterNullableAnnotation,
            expectedGeneratedCount,
            NullableSetup.Enable,
            PragmaWarning.NoBlock,
            bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method.
    /// </summary>
    /// <param name="this">The compilation unit syntax assertions.</param>
    /// <param name="className">The name of the class.</param>
    /// <param name="classModifiers">The class modifiers.</param>
    /// <param name="methodName">The name of the method.</param>
    /// <param name="methodModifiers">The method modifiers.</param>
    /// <param name="isExtensionMethod">The method is an extension method.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The nullable annotation on the return type.</param>
    /// <param name="parameterName">The name of the parameter.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="contextName">The (optional) name of the context.</param>
    /// <param name="parameterNullableAnnotation">The nullable annotation of the parameter.</param>
    /// <param name="expectedGeneratedCount">The number of expected methods generated.</param>
    /// <param name="nullableSetup">The nullable setup.</param>
    /// <param name="pragmaWarningSetting">The pragma warning settings.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string className,
        SyntaxKind[] classModifiers,
        string methodName,
        SyntaxKind[] methodModifiers,
        bool isExtensionMethod,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterName,
        string parameterType,
        string? contextName,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedCount,
        NullableSetup nullableSetup,
        PragmaWarning pragmaWarningSetting,
        Action<BlockSyntaxAssertions> bodyAssertion)
    {
        ArgumentNullException.ThrowIfNull(@this);

        return @this.HaveCommentHeader()
            .HaveFileScopedNamespace(fileScopedNamespaceDeclarationSyntaxAssertions =>
            {
                fileScopedNamespaceDeclarationSyntaxAssertions
                    .HaveClasses(1)
                    .HaveClass(
                        className,
                        classDeclarationSyntaxAssertions =>
                        {
                            var parameters = new List<(string Type, NullableAnnotation NullableAnnotation, string Name)>
                            {
                                (parameterType, parameterNullableAnnotation, parameterName),
                            };

                            if (contextName is not null)
                            {
                                parameters.Add((typeof(MappaContext).FullName ?? string.Empty, NullableAnnotation.NotAnnotated, contextName));
                            }

                            classDeclarationSyntaxAssertions
                                .HaveModifiers(classModifiers)
                                .HaveMethods(expectedGeneratedCount)
                                .HaveMethod(
                                    returnType,
                                    returnTypeNullableAnnotation,
                                    methodName,
                                    isExtensionMethod,
                                    parameters.ToArray(),
                                    methodDeclarationSyntaxAssertions =>
                                    {
                                        methodDeclarationSyntaxAssertions
                                            .HaveNullabilityAnnotation(nullableSetup)
                                            .HavePragmaWarningDisableAnnotation(pragmaWarningSetting)
                                            .HaveGeneratedCodeAttribute(attributeSyntaxAssertions => attributeSyntaxAssertions.BeMappaGeneratedCodeAttribute())
                                            .HaveDebuggerNonUserCodeAttribute()
                                            .HaveModifiers(methodModifiers)
                                            .HaveBody(bodyAssertion);
                                    });
                        });
            });
    }

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethodWithContext(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => HaveDefaultMapMethodWithContext(@this, returnType, returnTypeNullableAnnotation, parameterType, parameterNullableAnnotation, 1, bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="expectedGeneratedMethodsCount">The expected number of generated methods.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    public static CompilationUnitSyntaxAssertions HaveDefaultMapMethodWithContext(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedMethodsCount,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveDefaultMapMethodWithContext(
            returnType,
            returnTypeNullableAnnotation,
            parameterType,
            parameterNullableAnnotation,
            expectedGeneratedMethodsCount,
            false,
            bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method.
    /// </summary>
    /// <param name="this">The compilation unit syntax assertions.</param>
    /// <param name="className">The name of the class.</param>
    /// <param name="classModifiers">The class modifiers.</param>
    /// <param name="methodName">The name of the method.</param>
    /// <param name="methodModifiers">The method modifiers.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The nullable annotation on the return type.</param>
    /// <param name="parameterName">The name of the parameter.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The nullable annotation of the parameter.</param>
    /// <param name="expectedGeneratedCount">The number of expected methods generated.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    private static CompilationUnitSyntaxAssertions HaveMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string className,
        SyntaxKind[] classModifiers,
        string methodName,
        SyntaxKind[] methodModifiers,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterName,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedCount,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveMapMethod(
            className,
            classModifiers,
            methodName,
            methodModifiers,
            false,
            returnType,
            returnTypeNullableAnnotation,
            parameterName,
            parameterType,
            null,
            parameterNullableAnnotation,
            expectedGeneratedCount,
            NullableSetup.Enable,
            PragmaWarning.NoBlock,
            bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="expectedGeneratedMethodsCount">The expected number of generated methods.</param>
    /// <param name="isExtensionMethod">The method is an extension method.</param>
    /// <param name="nullableSetup">The nullable setup.</param>
    /// <param name="pragmaWarningSetting">The pragma warning settings.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    private static CompilationUnitSyntaxAssertions HaveDefaultMapMethod(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedMethodsCount,
        bool isExtensionMethod,
        NullableSetup nullableSetup,
        PragmaWarning pragmaWarningSetting,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveMapMethod(
            "Mapper",
            [SyntaxKind.PublicKeyword, SyntaxKind.SealedKeyword, SyntaxKind.PartialKeyword],
            "Map",
            [SyntaxKind.PublicKeyword, SyntaxKind.PartialKeyword],
            isExtensionMethod,
            returnType,
            returnTypeNullableAnnotation,
            "input",
            parameterType,
            null,
            parameterNullableAnnotation,
            expectedGeneratedMethodsCount,
            nullableSetup,
            pragmaWarningSetting,
            bodyAssertion);

    /// <summary>
    /// Assert that the compilation unit has a mapper method using default values.
    /// </summary>
    /// <param name="this">The compilation unit assertions.</param>
    /// <param name="returnType">The return type of the method.</param>
    /// <param name="returnTypeNullableAnnotation">The return type nullable annotation.</param>
    /// <param name="parameterType">The parameter type of the method.</param>
    /// <param name="parameterNullableAnnotation">The parameter nullable annotation.</param>
    /// <param name="expectedGeneratedMethodsCount">The expected number of generated methods.</param>
    /// <param name="isExtensionMethod">The method is an extension method.</param>
    /// <param name="bodyAssertion">The assertions on the body of the method.</param>
    /// <returns>The input compilation unit syntax assertions.</returns>
    private static CompilationUnitSyntaxAssertions HaveDefaultMapMethodWithContext(
        this CompilationUnitSyntaxAssertions @this,
        string returnType,
        NullableAnnotation returnTypeNullableAnnotation,
        string parameterType,
        NullableAnnotation parameterNullableAnnotation,
        int expectedGeneratedMethodsCount,
        bool isExtensionMethod,
        Action<BlockSyntaxAssertions> bodyAssertion)
        => @this.HaveMapMethod(
            "Mapper",
            [SyntaxKind.PublicKeyword, SyntaxKind.SealedKeyword, SyntaxKind.PartialKeyword],
            "Map",
            [SyntaxKind.PublicKeyword, SyntaxKind.PartialKeyword],
            isExtensionMethod,
            returnType,
            returnTypeNullableAnnotation,
            "input",
            parameterType,
            "context",
            parameterNullableAnnotation,
            expectedGeneratedMethodsCount,
            NullableSetup.Enable,
            PragmaWarning.NoBlock,
            bodyAssertion);
}