// <copyright file="OptionalTargetPropertyMapStrategyBuilder.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

using Mappa.Generator.Helpers;
using Mappa.Generator.Models;
using Mappa.Generator.Models.Strategies;

using PrettyCode;

namespace Mappa.Generator.Builders.Strategies;

/// <summary>
/// Builder for strategy <see cref="OptionalTargetPropertyMapStrategy"/>.
/// </summary>
internal sealed class OptionalTargetPropertyMapStrategyBuilder
    : IMappaStrategyBuilder
{
    private readonly OptionalTargetPropertyMapStrategy strategy;

    /// <summary>
    /// Initializes a new instance of the <see cref="OptionalTargetPropertyMapStrategyBuilder"/> class.
    /// </summary>
    /// <param name="strategy">The strategy.</param>
    public OptionalTargetPropertyMapStrategyBuilder(OptionalTargetPropertyMapStrategy strategy)
    {
        this.strategy = strategy;
    }

    /// <inheritdoc/>
    public (string VariableName, string Code) BuildSource(string source, MappaBuilderContext context, MappaGlobalOptions mappaGlobalOptions)
    {
        var builder = new StringBuilder();

        // source can be not defined if the target is generated by some constant values
        // in that case we check that  the generated value is not default
        if (string.IsNullOrWhiteSpace(source))
        {
            var (innerStrategyVariableName, innerStrategyCode) = this.strategy.InnerStrategy.GetBuilder().BuildSource(source, context, mappaGlobalOptions);
            if (!string.IsNullOrWhiteSpace(innerStrategyCode))
            {
                builder.AppendLine(innerStrategyCode);
                builder.AppendEmptyLine();
            }

            builder.AppendLine($"if ({innerStrategyVariableName} != default)");
            using (builder.CurlyBracesBlock())
            {
                builder.AppendLine(InaccessibleMemberAccessHelper.BuildPropertyAssignmentStatement(
                    context.GetCompositeTypeTargetName(),
                    this.strategy.TargetProperty,
                    innerStrategyVariableName,
                    context.RequiresUnsafeAccessorOnCurrentTargetProperty,
                    context));
            }
        }

        // If source is available we check that source variable
        // has a value. Condition can be the source optional if the inner
        // strategy is source optional or the source not equal to default.
        else
        {
            builder.AppendLine($"if ({this.GetCondition(source, context)})");
            using (builder.CurlyBracesBlock())
            {
                var (innerStrategyVariableName, innerStrategyCode) = this.GetStrategy().GetBuilder().BuildSource(source, context, mappaGlobalOptions);
                if (!string.IsNullOrWhiteSpace(innerStrategyCode))
                {
                    builder.AppendLine(innerStrategyCode);
                    builder.AppendEmptyLine();
                }

                builder.AppendLine(InaccessibleMemberAccessHelper.BuildPropertyAssignmentStatement(
                    context.GetCompositeTypeTargetName(),
                    this.strategy.TargetProperty,
                    innerStrategyVariableName,
                    context.RequiresUnsafeAccessorOnCurrentTargetProperty,
                    context));
            }
        }

        return (string.Empty, builder.ToString());
    }

    private string GetCondition(string source, MappaBuilderContext context)
    {
        if (this.strategy.InnerStrategy is OptionalSourcePropertyMapStrategy optionalSourcePropertyMapStrategy)
        {
            return $"{context.GetCompositeTypeSourceName()}.Has{optionalSourcePropertyMapStrategy.SourceProperty.Name}";
        }

        return $"{source} != default";
    }

    private MapStrategy GetStrategy()
    {
        if (this.strategy.InnerStrategy is OptionalSourcePropertyMapStrategy optionalSourcePropertyMapStrategy)
        {
            return optionalSourcePropertyMapStrategy.InnerStrategy;
        }

        return this.strategy.InnerStrategy;
    }
}