//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mappa.Generator.Diagnostics {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticsResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticsResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mappa.Generator.Diagnostics.DiagnosticsResources", typeof(DiagnosticsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MethodHasInvalidNumberOfParameters {
            get {
                return ResourceManager.GetString("MethodHasInvalidNumberOfParameters", resourceCulture);
            }
        }
        
        internal static string MethodHasInvalidMappaContextParameter {
            get {
                return ResourceManager.GetString("MethodHasInvalidMappaContextParameter", resourceCulture);
            }
        }
        
        internal static string MethodIsVoid {
            get {
                return ResourceManager.GetString("MethodIsVoid", resourceCulture);
            }
        }
        
        internal static string MethodReturnsTaskType {
            get {
                return ResourceManager.GetString("MethodReturnsTaskType", resourceCulture);
            }
        }
        
        internal static string DuplicatedMapping {
            get {
                return ResourceManager.GetString("DuplicatedMapping", resourceCulture);
            }
        }
    }
}
