//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mappa.Generator.Diagnostics {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticsResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticsResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mappa.Generator.Diagnostics.DiagnosticsResources", typeof(DiagnosticsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MethodHasInvalidNumberOfParameters {
            get {
                return ResourceManager.GetString("MethodHasInvalidNumberOfParameters", resourceCulture);
            }
        }
        
        internal static string MethodHasInvalidMappaContextParameter {
            get {
                return ResourceManager.GetString("MethodHasInvalidMappaContextParameter", resourceCulture);
            }
        }
        
        internal static string MethodIsVoid {
            get {
                return ResourceManager.GetString("MethodIsVoid", resourceCulture);
            }
        }
        
        internal static string MethodReturnsTaskType {
            get {
                return ResourceManager.GetString("MethodReturnsTaskType", resourceCulture);
            }
        }
        
        internal static string DuplicatedMapping {
            get {
                return ResourceManager.GetString("DuplicatedMapping", resourceCulture);
            }
        }
        
        internal static string CannotIdentifyStrategy {
            get {
                return ResourceManager.GetString("CannotIdentifyStrategy", resourceCulture);
            }
        }
        
        internal static string MultipleAttributesTargetTheSamePropertyOrParameter {
            get {
                return ResourceManager.GetString("MultipleAttributesTargetTheSamePropertyOrParameter", resourceCulture);
            }
        }
        
        internal static string CannotDetectSuitableMethodToInvokeForParameter {
            get {
                return ResourceManager.GetString("CannotDetectSuitableMethodToInvokeForParameter", resourceCulture);
            }
        }
        
        internal static string CannotDetectType {
            get {
                return ResourceManager.GetString("CannotDetectType", resourceCulture);
            }
        }
        
        internal static string CannotFindFieldOrProperty {
            get {
                return ResourceManager.GetString("CannotFindFieldOrProperty", resourceCulture);
            }
        }
        
        internal static string CannotUseMappaAssignFromContextAttributeWithoutContextParameter {
            get {
                return ResourceManager.GetString("CannotUseMappaAssignFromContextAttributeWithoutContextParameter", resourceCulture);
            }
        }
        
        internal static string UserDefinedCultureIsMissingCultureName {
            get {
                return ResourceManager.GetString("UserDefinedCultureIsMissingCultureName", resourceCulture);
            }
        }
        
        internal static string ParseExactDoesNotAcceptOnlyFormat {
            get {
                return ResourceManager.GetString("ParseExactDoesNotAcceptOnlyFormat", resourceCulture);
            }
        }
        
        internal static string PropertySetterIsNotAccessible {
            get {
                return ResourceManager.GetString("PropertySetterIsNotAccessible", resourceCulture);
            }
        }
        
        internal static string TooManyUsePropertyAttributesForTheSameTargetProperty {
            get {
                return ResourceManager.GetString("TooManyUsePropertyAttributesForTheSameTargetProperty", resourceCulture);
            }
        }
        
        internal static string DependencyDoesNotProvideAnyViableMethod {
            get {
                return ResourceManager.GetString("DependencyDoesNotProvideAnyViableMethod", resourceCulture);
            }
        }
        
        internal static string CannotMapNonRequiredProperty {
            get {
                return ResourceManager.GetString("CannotMapNonRequiredProperty", resourceCulture);
            }
        }
        
        internal static string ExplicitTargetTypeDoesNotDeriveMapMethodTargetType {
            get {
                return ResourceManager.GetString("ExplicitTargetTypeDoesNotDeriveMapMethodTargetType", resourceCulture);
            }
        }
        
        internal static string MethodToInvokeUndefined {
            get {
                return ResourceManager.GetString("MethodToInvokeUndefined", resourceCulture);
            }
        }
        
        internal static string CannotIdentifySuitableMethodToInvoke {
            get {
                return ResourceManager.GetString("CannotIdentifySuitableMethodToInvoke", resourceCulture);
            }
        }
        
        internal static string TypeMustBeAnException {
            get {
                return ResourceManager.GetString("TypeMustBeAnException", resourceCulture);
            }
        }
        
        internal static string TypeMustBeConcrete {
            get {
                return ResourceManager.GetString("TypeMustBeConcrete", resourceCulture);
            }
        }
        
        internal static string TypeMustHaveAConstructorWithNoParametersOrAConstructorWithOneStringParameter {
            get {
                return ResourceManager.GetString("TypeMustHaveAConstructorWithNoParametersOrAConstructorWithOneStringParameter", resourceCulture);
            }
        }
        
        internal static string MappaTypeDefaultBehaviorUndefined {
            get {
                return ResourceManager.GetString("MappaTypeDefaultBehaviorUndefined", resourceCulture);
            }
        }
        
        internal static string MappaTypeMappingDefaultAttributeUnusedType {
            get {
                return ResourceManager.GetString("MappaTypeMappingDefaultAttributeUnusedType", resourceCulture);
            }
        }
        
        internal static string MappaTypeMappingAttributeHaveTheSameSourceType {
            get {
                return ResourceManager.GetString("MappaTypeMappingAttributeHaveTheSameSourceType", resourceCulture);
            }
        }
        
        internal static string MappaTypeMappingAttributeMapsSourceType {
            get {
                return ResourceManager.GetString("MappaTypeMappingAttributeMapsSourceType", resourceCulture);
            }
        }
        
        internal static string MappaTypeMappingAttributeSourceTypeNotDeriveOrImplementMapMethodSourceType {
            get {
                return ResourceManager.GetString("MappaTypeMappingAttributeSourceTypeNotDeriveOrImplementMapMethodSourceType", resourceCulture);
            }
        }
        
        internal static string MappaTypeMappingAttributeTargetTypeNotDeriveOrImplementMapMethodTargetType {
            get {
                return ResourceManager.GetString("MappaTypeMappingAttributeTargetTypeNotDeriveOrImplementMapMethodTargetType", resourceCulture);
            }
        }
        
        internal static string FieldOrPropertyMustBeStatic {
            get {
                return ResourceManager.GetString("FieldOrPropertyMustBeStatic", resourceCulture);
            }
        }
        
        internal static string MappaUsePropertySourcePropertyWillNotBeUsed {
            get {
                return ResourceManager.GetString("MappaUsePropertySourcePropertyWillNotBeUsed", resourceCulture);
            }
        }
        
        internal static string MappaUsePropertyNotUsedByInvokeMethod {
            get {
                return ResourceManager.GetString("MappaUsePropertyNotUsedByInvokeMethod", resourceCulture);
            }
        }
        
        internal static string MappingAttributeTargetPropertyOrParameterDoesNotExist {
            get {
                return ResourceManager.GetString("MappingAttributeTargetPropertyOrParameterDoesNotExist", resourceCulture);
            }
        }
        
        internal static string TooManyMappaIgnoreTargetPropertyAttributesForTheSameTargetProperty {
            get {
                return ResourceManager.GetString("TooManyMappaIgnoreTargetPropertyAttributesForTheSameTargetProperty", resourceCulture);
            }
        }
        
        internal static string MappaAssignToContextTargetMemberDoesNotExistOrIsNotAccessible {
            get {
                return ResourceManager.GetString("MappaAssignToContextTargetMemberDoesNotExistOrIsNotAccessible", resourceCulture);
            }
        }
        
        internal static string CannotUseMappaAssignToContextAttributeWithoutContextParameter {
            get {
                return ResourceManager.GetString("CannotUseMappaAssignToContextAttributeWithoutContextParameter", resourceCulture);
            }
        }
        
        internal static string MultipleMappaAssignToContextAttributesUseTheSameContextKey {
            get {
                return ResourceManager.GetString("MultipleMappaAssignToContextAttributesUseTheSameContextKey", resourceCulture);
            }
        }

        internal static string InvalidMappaSettingsStyleValue {
            get {
                return ResourceManager.GetString("InvalidMappaSettingsStyleValue", resourceCulture);
            }
        }

        internal static string NotAllSourceEnumMembersCanBeMapped {
            get {
                return ResourceManager.GetString("NotAllSourceEnumMembersCanBeMapped", resourceCulture);
            }
        }

        internal static string EnumMemberMissingDescription {
            get {
                return ResourceManager.GetString("EnumMemberMissingDescription", resourceCulture);
            }
        }

        internal static string AmbiguousEnumMap {
            get {
                return ResourceManager.GetString("AmbiguousEnumMap", resourceCulture);
            }
        }

        internal static string AmbiguousInvokeMethodResolution {
            get {
                return ResourceManager.GetString("AmbiguousInvokeMethodResolution", resourceCulture);
            }
        }

        internal static string MappingAttributeSourcePropertyPathIsShorterThanTargetPropertyPath {
            get {
                return ResourceManager.GetString("MappingAttributeSourcePropertyPathIsShorterThanTargetPropertyPath", resourceCulture);
            }
        }

        internal static string MappingAttributeSourcePropertyPathSegmentDoesNotExist {
            get {
                return ResourceManager.GetString("MappingAttributeSourcePropertyPathSegmentDoesNotExist", resourceCulture);
            }
        }

        internal static string HookMethodNotFound {
            get {
                return ResourceManager.GetString("HookMethodNotFound", resourceCulture);
            }
        }

        internal static string DuplicateMapHookRegistration {
            get {
                return ResourceManager.GetString("DuplicateMapHookRegistration", resourceCulture);
            }
        }

        internal static string EnumMapAttributeEnumTypeMismatch {
            get {
                return ResourceManager.GetString("EnumMapAttributeEnumTypeMismatch", resourceCulture);
            }
        }

        internal static string EnumMapMemberMappingClash {
            get {
                return ResourceManager.GetString("EnumMapMemberMappingClash", resourceCulture);
            }
        }

        internal static string EnumMapIgnoreConflictsWithMemberMapping {
            get {
                return ResourceManager.GetString("EnumMapIgnoreConflictsWithMemberMapping", resourceCulture);
            }
        }

        internal static string EnumMapDefaultBehaviorRequiresDefaultValue {
            get {
                return ResourceManager.GetString("EnumMapDefaultBehaviorRequiresDefaultValue", resourceCulture);
            }
        }

        internal static string EnumMapDefaultValueConstructorMismatch {
            get {
                return ResourceManager.GetString("EnumMapDefaultValueConstructorMismatch", resourceCulture);
            }
        }

        internal static string EnumMapDefaultAttributeUnusedDefaultValue {
            get {
                return ResourceManager.GetString("EnumMapDefaultAttributeUnusedDefaultValue", resourceCulture);
            }
        }

        internal static string TooManyEnumMapDefaultAttributesOnDirectEnumMap {
            get {
                return ResourceManager.GetString("TooManyEnumMapDefaultAttributesOnDirectEnumMap", resourceCulture);
            }
        }

        internal static string DuplicateEnumMapDefaultAttribute {
            get {
                return ResourceManager.GetString("DuplicateEnumMapDefaultAttribute", resourceCulture);
            }
        }

        internal static string ProjectionMethodHasBeforeOrAfterMapHooks {
            get {
                return ResourceManager.GetString("ProjectionMethodHasBeforeOrAfterMapHooks", resourceCulture);
            }
        }

        internal static string ProjectionMethodHasMappaContextParameter {
            get {
                return ResourceManager.GetString("ProjectionMethodHasMappaContextParameter", resourceCulture);
            }
        }

        internal static string ProjectionMappingNotSupported {
            get {
                return ResourceManager.GetString("ProjectionMappingNotSupported", resourceCulture);
            }
        }

        internal static string ProjectionInvokeMethodNotInlinable {
            get {
                return ResourceManager.GetString("ProjectionInvokeMethodNotInlinable", resourceCulture);
            }
        }

        internal static string ProjectionNestedQueryableNotSupported {
            get {
                return ResourceManager.GetString("ProjectionNestedQueryableNotSupported", resourceCulture);
            }
        }

        internal static string ProjectionEnumStrategyNotSupported {
            get {
                return ResourceManager.GetString("ProjectionEnumStrategyNotSupported", resourceCulture);
            }
        }

        internal static string IQueryableMappedAsCollection {
            get {
                return ResourceManager.GetString("IQueryableMappedAsCollection", resourceCulture);
            }
        }

        internal static string DuplicateObjectFactoryForTargetType {
            get {
                return ResourceManager.GetString("DuplicateObjectFactoryForTargetType", resourceCulture);
            }
        }

        internal static string ObjectFactoryMethodNotFound {
            get {
                return ResourceManager.GetString("ObjectFactoryMethodNotFound", resourceCulture);
            }
        }

        internal static string ProjectionMethodHasObjectFactory {
            get {
                return ResourceManager.GetString("ProjectionMethodHasObjectFactory", resourceCulture);
            }
        }

        internal static string MustMapTargetPropertyWasNotMapped {
            get {
                return ResourceManager.GetString("MustMapTargetPropertyWasNotMapped", resourceCulture);
            }
        }

        internal static string MappaMustMapTargetPropertyListsRequiredProperty {
            get {
                return ResourceManager.GetString("MappaMustMapTargetPropertyListsRequiredProperty", resourceCulture);
            }
        }
    }
}