// <copyright file="IdentityStrategyUnitTest.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

namespace Mappa.Tests;

/// <summary>
/// Tests related to the identity strategy.
/// </summary>
public sealed class IdentityStrategyUnitTest
    : Abstractions.MappaGeneratorAbstractUnitTests
{
    /// <summary>
    /// Test a mapping can be created from reference type
    /// to <see cref="object"/>.
    /// </summary>
    /// <returns>The async task.</returns>
    [Fact]
    [IntegrationTest]
    public async Task CanMapReferenceTypeToObjectWhenNullableDisabled()
    {
        // Arrange
        var sourceCode = """
            #nullable disable
            using Mappa.Attributes;

            namespace Mappa.Tests.UnitTests.SourceCode;

            [Mappa]
            public sealed partial class Mapper
            {
                public partial object Map(string input);
            }
            """;

        // Act
        var generatedResults = await RunMappaGeneratorAsync(sourceCode, CancellationToken.None).ConfigureAwait(true);

        // Assert
        generatedResults.Should()
            .NotHaveDiagnostics()
            .HaveGeneratedOneSourceCode();

        #pragma warning disable
        var syntaxTree = generatedResults.OutputCompilation.SyntaxTrees.Last();
        generatedResults.OutputCompilation.GetSemanticModel(syntaxTree);

        var root = await syntaxTree.GetRootAsync(CancellationToken.None).ConfigureAwait(true);
        root.HasLeadingTrivia.Should().BeTrue();
        var leadingTrivia = root.GetLeadingTrivia()
            .Select(trivia => trivia.ToString())
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .ToArray();
        leadingTrivia.Should().HaveCount(6);
        leadingTrivia[0].Should().Be("// <auto-generated>");
        leadingTrivia[1].Should().Be("//    <tool-name>Mappa</tool-name>");
        leadingTrivia[2].Should().Be($"//    <tool-version>{MappaGeneratorConsts.MappaGeneratorVersion}</tool-version>");
        leadingTrivia[3].Should().Match($"^\\/\\/    \\<timestamp\\>(?<duplicateWord>.*)\\<\\/timestamp\\>");
        leadingTrivia[4].Should().Be("//    <note>This is an autogenerated file: edit to this file might be lost.</note>");
        leadingTrivia[5].Should().Be("// </auto-generated>");

        foreach (var node in root.ChildNodes())
        {
            
        }
    }
}