// <copyright file="IdentityStrategyUnitTest.cs" company="Stefano Anelli">
// Copyright (c) Stefano Anelli. All rights reserved.
// </copyright>

using System.CodeDom.Compiler;

using Mappa.Generator.Extensions;

using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mappa.Tests;

/// <summary>
/// Tests related to the identity strategy.
/// </summary>
public sealed class IdentityStrategyUnitTest
    : Abstractions.MappaGeneratorAbstractUnitTests
{
    /// <summary>
    /// Test a mapping can be created from reference type
    /// to <see cref="object"/>.
    /// </summary>
    /// <returns>The async task.</returns>
    [Fact]
    [IntegrationTest]
    public async Task CanMapReferenceTypeToObjectWhenNullableDisabled()
    {
        // Arrange
        var sourceCode = """
            #nullable disable
            using Mappa.Attributes;

            namespace Mappa.Tests.UnitTests.SourceCode;

            [Mappa]
            public sealed partial class Mapper
            {
                public partial object Map(string input);
            }
            #nullable restore
            """;

        // Act
        var generatedResults = await RunMappaGeneratorAsync(sourceCode, CancellationToken.None).ConfigureAwait(true);

        // Assert
        generatedResults.Should()
            .NotHaveDiagnostics()
            .HaveGeneratedOneSourceCode();

        #pragma warning disable
        var syntaxTree = generatedResults.OutputCompilation.SyntaxTrees.Last();
        var semanticModel = generatedResults.OutputCompilation.GetSemanticModel(syntaxTree);

        var root = await syntaxTree.GetRootAsync(CancellationToken.None).ConfigureAwait(true);
        
        // Leading comment
        root.HasLeadingTrivia.Should().BeTrue();
        var leadingTrivia = root.GetLeadingTrivia()
            .Select(trivia => trivia.ToString())
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .ToArray();
        leadingTrivia.Should().HaveCount(6);
        var mappaGeneratorVersion = MappaGeneratorConsts.MappaGeneratorVersion?.ToString() ?? string.Empty;
        leadingTrivia[0].Should().Be("// <auto-generated>");
        leadingTrivia[1].Should().Be("//    <tool-name>Mappa</tool-name>");
        leadingTrivia[2].Should().Be($"//    <tool-version>{mappaGeneratorVersion}</tool-version>");
        leadingTrivia[3].Should().MatchRegex("\\/\\/    \\<timestamp\\>(.*)\\<\\/timestamp\\>");
        leadingTrivia[4].Should().Be("//    <note>This is an autogenerated file: edit to this file might be lost.</note>");
        leadingTrivia[5].Should().Be("// </auto-generated>");

        // Namespace
        var fileScopedNamespaceDeclarationSyntaxes = root.ChildNodes().OfType<FileScopedNamespaceDeclarationSyntax>().ToArray();
        fileScopedNamespaceDeclarationSyntaxes.Should().HaveCount(1);
        var fileScopedNamespaceDeclarationSyntax = fileScopedNamespaceDeclarationSyntaxes.Single();
        fileScopedNamespaceDeclarationSyntax.Name.ToString().Should().Be("Mappa.Tests.UnitTests.SourceCode");
        
        // Class
        var classDeclarationSyntaxes = fileScopedNamespaceDeclarationSyntax.ChildNodes().OfType<ClassDeclarationSyntax>().ToArray();
        classDeclarationSyntaxes.Should().HaveCount(1);
        var classDeclarationSyntax = classDeclarationSyntaxes.Single();
        
        // Class definition
        var expectedClassModifiers = new HashSet<SyntaxKind>
        {
            SyntaxKind.PublicKeyword,
            SyntaxKind.SealedKeyword,
            SyntaxKind.PartialKeyword,
        };
        classDeclarationSyntax.Modifiers.Should().HaveCount(expectedClassModifiers.Count);
        classDeclarationSyntax.Modifiers.Should()
            .Contain(syntaxToken => expectedClassModifiers.Contains(syntaxToken.Kind()));
        classDeclarationSyntax.Identifier.ToString().Should().Be("Mapper");
        
        // Class has attribute
        classDeclarationSyntax.AttributeLists.Should().HaveCount(1);
        var classAttributeList = classDeclarationSyntax.AttributeLists.Single();
        classAttributeList.Attributes.Should().HaveCount(1);
        var classAttribute = classAttributeList.Attributes.Single();
        classAttribute.Name.ToString().Should().Be(typeof(GeneratedCodeAttribute).FullName);
        classAttribute.ArgumentList.Arguments.Should().HaveCount(2);
        classAttribute.ArgumentList.Arguments.First().GetText().ToString().Should().Be("\"Mappa\"");
        classAttribute.ArgumentList.Arguments.Last().GetText().ToString().Should().Be($"\"{MappaGeneratorConsts.MappaGeneratorVersion.ToString()}\"");

        // Method
        var methodDeclarationSyntaxes = classDeclarationSyntax.ChildNodes().OfType<MethodDeclarationSyntax>().ToArray();
        methodDeclarationSyntaxes.Should().HaveCount(1);
        var methodDeclarationSyntax = methodDeclarationSyntaxes.Single();
        
        // Method attributes
        methodDeclarationSyntax.AttributeLists.Should().HaveCount(1);
        var methodAttributeList = methodDeclarationSyntax.AttributeLists.Single();
        methodAttributeList.Attributes.Should().HaveCount(1);
        var methodAttribute = methodAttributeList.Attributes.Single();
        methodAttribute.Name.ToString().Should().Be(typeof(GeneratedCodeAttribute).FullName);
        methodAttribute.ArgumentList.Arguments.Should().HaveCount(2);
        methodAttribute.ArgumentList.Arguments.Should().HaveCount(2);
        methodAttribute.ArgumentList.Arguments.First().GetText().ToString().Should().Be("\"Mappa\"");
        methodAttribute.ArgumentList.Arguments.Last().GetText().ToString().Should().Be($"\"{MappaGeneratorConsts.MappaGeneratorVersion.ToString()}\"");   
        
        // Method signature
        var expectedMethodModifier = new HashSet<SyntaxKind>
        {
            SyntaxKind.PartialKeyword,
            SyntaxKind.PublicKeyword
        };
        methodDeclarationSyntax.Modifiers.Should().HaveCount(expectedMethodModifier.Count);
        methodDeclarationSyntax.Modifiers.Should()
            .Contain(syntaxToken => expectedMethodModifier.Contains(syntaxToken.Kind()));
        methodDeclarationSyntax.Identifier.ToString().Should().Be("Map");
        methodDeclarationSyntax.ParameterList.Parameters.Should().HaveCount(1);
        var methodSymbol = semanticModel.GetDeclaredSymbol(methodDeclarationSyntax);
        methodSymbol.Parameters.Should().HaveCount(1);
        methodSymbol.Parameters.First().Name.Should().Be("input");
        SymbolEqualityComparer.Default.Equals(
            methodSymbol.Parameters.First().Type.IsDefinition ? methodSymbol.Parameters.First().Type : methodSymbol.Parameters.First().OriginalDefinition,
            generatedResults.OutputCompilation.GetTypeSymbol<string>())
            .Should().BeTrue();

        // Method body content
        var methodBody = methodDeclarationSyntax.ChildNodes().OfType<BlockSyntax>().Single();
        methodBody.ChildNodes().Should().HaveCount(1);
        var returnStatement = methodBody.ChildNodes().OfType<ReturnStatementSyntax>().Single();
        returnStatement.Expression.Should().BeOfType<IdentifierNameSyntax>();
        ((IdentifierNameSyntax)returnStatement.Expression).Identifier.Text.Should().Be("input");
    }
}