<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AnalysisLevel>latest-all</AnalysisLevel>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.0" />
		<PackageReference Include="xunit" Version="2.4.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="3.2.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="SonarAnalyzer.CSharp" Version="8.49.0.57237">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" Version="6.8.0" />
		<PackageReference Include="xunit.categories" Version="2.0.6" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" />
		<PackageReference Include="XunitXml.TestLogger" Version="3.0.70" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Mappa.Generator\Mappa.Generator.csproj" />
		<ProjectReference Include="..\Mappa\Mappa.csproj" />
	</ItemGroup>
	<ItemGroup>
		<AdditionalFiles Include="../stylecop.json" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Abstractions\" />
	  <None Remove="xunit.categories" />
	  <None Remove="Microsoft.CodeAnalysis.CSharp" />
	  <None Remove="Models\" />
	  <None Remove="Assertions\" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Abstractions\" />
	  <Folder Include="Models\" />
	  <Folder Include="Assertions\" />
	</ItemGroup>
</Project>