name: Build main

on:
  push:
    branches: [ "main" ]

jobs:
  code-coverage:
    name: Main Build Coverage and Benchmarks
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Initialize NuGet.Config
        shell: pwsh
        run:
          ./Scripts/CreateNuGetConfig.ps1
      - name: Build
        shell: pwsh
        run: ./Scripts/RebuildUponVersionChange.ps1
      - name: Test and code coverage
        shell: pwsh
        run: ./Scripts/RunTestsAndReportCoverage.ps1 -AlwaysSuccess
      - name: Update code coverage Gist
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: ./Scripts/UpdateCodeCoverageGists.ps1
      - name: Run benchmarks
        shell: pwsh
        run: ./Scripts/RunBenchmarks.ps1 -ChartBenchmarksOnly
      - name: Update benchmark Gist
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: ./Scripts/UpdateBenchmarkGists.ps1
