name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: PR Build and Test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v6
      - name: Fetch main
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Check version has been increased
        shell: pwsh
        run: ./Scripts/CheckVersionIncrease.ps1
      - name: Initialize NuGet.Config
        shell: pwsh
        run:
          ./Scripts/CreateNuGetConfig.ps1
      - name: Force check that TODOs have been addressed
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        shell: pwsh
        run: ./Scripts/ForceTodoErrorForBranch.ps1
      - name: Build
        shell: pwsh
        run: ./Scripts/RebuildUponVersionChange.ps1
      - name: Test and code coverage
        shell: pwsh
        run: ./Scripts/RunTestsAndReportCoverage.ps1
      - name: Comment pull request coverage
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./Scripts/CommentPullRequestCoverage.ps1
