name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Publish Release Packages
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Check version is valid for release
        shell: pwsh
        env:
          RELEASE_VERSION: ${{ github.event.release.name }}
        run: ./Scripts/CheckReleaseVersion.ps1
      - name: Initialize NuGet.Config
        shell: pwsh
        run:
          ./Scripts/CreateNuGetConfig.ps1
      - name: Build Release Packages
        shell: pwsh
        run: ./Scripts/BuildRelease.ps1
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish Nuget packages
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "./.packages" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }